export const ErrorName = {
  'ok': 'ok',
  'argument_null': 'argument_null',
  'compute_invalid_ratingSystem': 'compute_invalid_ratingSystem',
  'db_delete_no_id': 'db_delete_no_id',
  'db_delete_fail': 'db_delete_fail',
  'db_error': 'db_error',
  'db_fail_create': 'db_fail_create',
  'db_fail_delete': 'db_fail_delete',
  'db_fail_fetchRange': 'db_fail_fetchRange',
  'db_fail_update': 'db_fail_update',
  'db_invalid_digit': 'db_invalid_digit',
  'db_invalid_key': 'db_invalid_key',
  'db_save_no_id': 'db_save_no_id',
  'db_add_id_to_auto_id': 'db_add_id_to_auto_id',
  'db_notFound': 'db_notFound',
  'db_unexpected_multiple': 'db_unexpected_multiple',
  'mo_mismatch': 'mo_mismatch',
  'id_mismatch': 'id_mismatch',
  'idGenerator_fail_setup_new_table': 'idGenerator_fail_setup_new_table',
  'field_invalid': 'field_invalid',
  'field_invalid_tooShort': 'field_invalid_tooShort',
  'field_invalid_tooLong': 'field_invalid_tooLong',
  'field_invalid_email': 'field_invalid_email',
  'field_invalid_key': 'field_invalid_key',
  'field_invalid_number': 'field_invalid_number',
  'field_invalid_numberTooLarge': 'field_invalid_numberTooLarge',
  'field_invalid_numberTooSmall': 'field_invalid_numberTooSmall',
  'field_unknown': 'field_unknown',
  'field_unsupported': 'field_unsupported',
  'gdrive_error': 'gdrive_error',
  'gdrive_missing_fileId': 'gdrive_missing_fileId',
  'gdrive_missing_id': 'gdrive_missing_id',
  'gdrive_file_notFound': 'gdrive_file_notFound',
  'missing_id': 'missing_id',
  'missing_field': 'missing_field',
  'missing_implementation': 'missing_implementation',
  'missing_param': 'missing_param',
  'missing_value': 'missing_value',
  'moMeta_notFound': 'moMeta_notFound',
  'not_implemented_in_default': 'not_implemented_in_default',
  'not_implemented_in_subclass': 'not_implemented_in_subclass',
  'req_invalid_action': 'req_invalid_action',
  'req_missing_id': 'req_missing_id',
  'req_no_id': 'req_no_id',
  'resource_not_found': 'resource_not_found',
  'server_error': 'server_error',
  'spreadsheet_no_name': 'spreadsheet_no_name',
  'type5_error': 'type5_error',
} as const
export type ErrorEnum = (typeof ErrorName)[keyof typeof ErrorName]


export const ErrorDef: {[name:string]: {[httpCode:string]:number}} = {
  ok: {httpCode: 200},
  compute_invalid_ratingSystem: {httpCode: 500},
  db_error: {},
  db_fail_create: {},
  db_fail_delete: {},
  db_fail_fetchRange: {},
  db_fail_update: {},
  db_invalid_digit: {},
  db_invalid_key: {},
  db_notFound: {},
  db_unexpected_multiple: {},
  mo_mismatch: {httpCode: 400},
  id_mismatch: {httpCode: 400},
  idGenerator_fail_setup_new_table: {},
  field_invalid: {httpCode: 400},
  field_invalid_email: {httpCode: 400},
  field_invalid_key: {httpCode: 400},
  field_invalid_number: {httpCode: 400},
  field_invalid_numberTooLarge: {httpCode: 400},
  field_invalid_numberTooSmall: {httpCode: 400},
  field_unknown: {httpCode: 400},
  field_unsupported: {httpCode: 400},
  moMeta_notFound: {httpCode: 400},
  not_implemented_in_subclass: {httpCode: 500},
  req_invalid_action: {httpCode: 400},
  req_missing_id: {httpCode: 400},
  req_no_id: {httpCode: 400},
  server_error: {httpCode: 500},
  type5_error: {httpCode: 505},
}
